name: deploy to ec2

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted


    steps: 
      - name: checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t cicd-web-app:latest .

      - name: Run new container (candidate)
        run: |
          docker rm -f web-new || true
          docker run -d --name web-new -p 8080:80 cicd-web-app:latest

      - name: Health check new container
        run: |
          sleep 5
          curl -f http://localhost:8080

      - name: Stop old container (free port 80)
        run: |
          docker rm -f web-current || true

      - name: Start new container on port 80
        run: |
          docker run -d --name web-current -p 80:80 cicd-web-app:latest

      - name: Cleanup 
        run: |
          docker rm -f web-new || true
