name: CI-CD to ECS

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    env:
      AWS_REGION: eu-north-1
      ECR_REPO: cicd-web-app
      ECS_CLUSTER: cicd-cluster
      ECS_SERVICE: CI-CD-service
      TASK_FAMILY: CI-CD

    steps: 
      - name: checkout code
        uses: actions/checkout@v3

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin \
            058264429057.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t $ECR_REPO:${{ github.sha }} .

      - name: Tag & push image
        run: |
            docker tag $ECR_REPO:${{ github.sha }} \
              058264429057.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:${{ github.sha }}
            docker push \
              058264429057.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:${{ github.sha }}

      - name: Update ECS Service
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $ECS_SERVICE \
            --force-new-deployment
