name: CI-CD to ECS

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    env:
      AWS_ACCOUNT_ID: 058264429057
      AWS_REGION: eu-north-1
      ECR_REPO: cicd-web-app
      ECS_CLUSTER: cicd-cluster
      ECS_SERVICE: CI-CD-service
      TASK_FAMILY: CI-CD

    steps: 
      - name: checkout code
        uses: actions/checkout@v3

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin \
            058264429057.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t $ECR_REPO:${{ github.sha }} .

      - name: Tag & push image
        run: |
            docker tag $ECR_REPO:${{ github.sha }} \
              058264429057.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:${{ github.sha }}
            docker push \
              058264429057.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:${{ github.sha }}


      - name: Download current task definition
        run: |
          aws ecs describe-task-definition \
            --region $AWS_REGION \
            --task-definition $TASK_FAMILY \
            --query taskDefinition \
            > task-def.json

      - name: Render new task definition
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq

          jq --arg IMAGE "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:${{ github.sha }}" \
            '.containerDefinitions[0].image = $IMAGE
             | del(.taskDefinitionArn,.revision,.status,.requiresAttributes,.compatibilities,.registeredAt,.registeredBy)' \
            task-def.json > new-task-def.json

      - name: Register new task definition
        run: |
          aws ecs register-task-definition \
            --region $AWS_REGION \
            --cli-input-json file://new-task-def.json

      - name: Deploy to ECS service
        run: |
          aws ecs update-service \
            --region $AWS_REGION \
            --cluster $ECS_CLUSTER \
            --service $ECS_SERVICE \
            --task-definition $TASK_FAMILY
